# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'xanmar' do
  pod 'Stripe', '~> 11.2.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for xanmar
  pod 'Firebase/Messaging'
  pod 'Google-Mobile-Ads-SDK'

  target 'xanmarTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
